# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "30...80"
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  go:
    partials_as_hits: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "**/*_test.go"
  - "test/**/*"
  - "cmd/g4d/main.go"
